export const SERVICE_TYPES = [
  "Accounting & Finance",
  "AC Repair",
  "Appliance Repair",
  "Arts & Crafts",
  "Beauty & Wellness",
  "Birthday Party Planner",
  "Carpentry & Woodwork",
  "Childcare",
  "Cleaning Services",
  "Construction & Repair",
  "Delivery & Courier",
  "Design",
  "Driving & Chauffeur",
  "Education & Tutoring",
  "Elderly Care",
  "Electrical Work",
  "Engineering & Technical",
  "Event Planning",
  "Event Services",
  "Food & Catering",
  "Gardening & Landscaping",
  "General Services",
  "Graphic Design",
  "Handyman Services",
  "Healthcare",
  "Home Assistant",
  "Home Services",
  "Interior Design",
  "IT & Software",
  "Laundry & Ironing",
  "Legal Services",
  "Literature & Writing",
  "Marketing & Advertising",
  "Mehendi / Mehandi",
  "Music & Performance",
  "Packing & Moving",
  "Painting & Decoration",
  "Personal Training",
  "Pet Care",
  "Pest Control",
  "Photography & Videography",
  "Plumbing",
  "Real Estate",
  "Security Services",
  "Software Development",
  "Tailoring & Fashion",
  "Transportation",
  "UX Design",
  "Yoga & Meditation",
  "Other"
];

export const isValidServiceType = (type) => {
  if (!type || typeof type !== "string") return false;
  return true; // Allow any string, including custom entries
};
